/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutTeamsImport } from './routes/_layout/teams'
import { Route as LayoutTeamImport } from './routes/_layout/team'
import { Route as LayoutSeasonsImport } from './routes/_layout/seasons'
import { Route as LayoutSeasonImport } from './routes/_layout/season'
import { Route as LayoutSearchImport } from './routes/_layout/search'
import { Route as LayoutMaratonImport } from './routes/_layout/maraton'
import { Route as LayoutDashboardImport } from './routes/_layout/dashboard'
import { Route as LayoutTeamsIndexImport } from './routes/_layout/teams/index'
import { Route as LayoutSearchIndexImport } from './routes/_layout/search/index'
import { Route as LayoutDashboardIndexImport } from './routes/_layout/dashboard/index'
import { Route as LayoutTeamsSelectionImport } from './routes/_layout/teams/selection'
import { Route as LayoutTeamsCompareImport } from './routes/_layout/teams/compare'
import { Route as LayoutTeamTeamIdImport } from './routes/_layout/team/$teamId'
import { Route as LayoutSeasonSeasonIdImport } from './routes/_layout/season/$seasonId'
import { Route as LayoutSearchHelpImport } from './routes/_layout/search/help'
import { Route as LayoutMaratonTableImport } from './routes/_layout/maraton/table'
import { Route as LayoutMaratonRecordsImport } from './routes/_layout/maraton/records'
import { Route as LayoutMaratonHelpImport } from './routes/_layout/maraton/help'
import { Route as LayoutDashboardSeasonsImport } from './routes/_layout/dashboard/seasons'
import { Route as LayoutDashboardNewSeasonImport } from './routes/_layout/dashboard/newSeason'
import { Route as LayoutDashboardErrorsImport } from './routes/_layout/dashboard/errors'
import { Route as LayoutDashboardAddTeamsImport } from './routes/_layout/dashboard/addTeams'
import { Route as LayoutMaratonRecordsIndexImport } from './routes/_layout/maraton/records/index'
import { Route as LayoutSeasonSeasonIdStatsImport } from './routes/_layout/season/$seasonId.stats'
import { Route as LayoutSeasonSeasonIdPlayoffImport } from './routes/_layout/season/$seasonId.playoff'
import { Route as LayoutSeasonSeasonIdMapImport } from './routes/_layout/season/$seasonId.map'
import { Route as LayoutSeasonSeasonIdGamesImport } from './routes/_layout/season/$seasonId.games'
import { Route as LayoutSeasonSeasonIdDevelopmentImport } from './routes/_layout/season/$seasonId.development'
import { Route as LayoutMaratonTableTableImport } from './routes/_layout/maraton/table/$table'
import { Route as LayoutMaratonRecordsStreaksImport } from './routes/_layout/maraton/records/streaks'
import { Route as LayoutMaratonRecordsScoredImport } from './routes/_layout/maraton/records/scored'
import { Route as LayoutMaratonRecordsPointsImport } from './routes/_layout/maraton/records/points'
import { Route as LayoutMaratonRecordsConcededImport } from './routes/_layout/maraton/records/conceded'
import { Route as LayoutDashboardSeasonSeasonIdImport } from './routes/_layout/dashboard/season/$seasonId'
import { Route as LayoutSeasonSeasonIdTablesIndexImport } from './routes/_layout/season/$seasonId/tables/index'
import { Route as LayoutDashboardSeasonSeasonIdIndexImport } from './routes/_layout/dashboard/season/$seasonId.index'
import { Route as LayoutDashboardSeasonSeasonIdTeamseasonImport } from './routes/_layout/dashboard/season/$seasonId.teamseason_'
import { Route as LayoutDashboardSeasonSeasonIdNewseriesImport } from './routes/_layout/dashboard/season/$seasonId.newseries'
import { Route as LayoutDashboardSeasonSeasonIdMetadataImport } from './routes/_layout/dashboard/season/$seasonId.metadata'
import { Route as LayoutDashboardSeasonSeasonIdBulkgamesImport } from './routes/_layout/dashboard/season/$seasonId.bulkgames'
import { Route as LayoutSeasonSeasonIdTablesTableTableImport } from './routes/_layout/season/$seasonId/tables/_table/$table'

// Create Virtual Routes

const LayoutUnauthorizedLazyImport = createFileRoute('/_layout/unauthorized')()
const LayoutAboutLazyImport = createFileRoute('/_layout/about')()
const LayoutTeamsMapLazyImport = createFileRoute('/_layout/teams/map')()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutUnauthorizedLazyRoute = LayoutUnauthorizedLazyImport.update({
  path: '/unauthorized',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/unauthorized.lazy').then((d) => d.Route),
)

const LayoutAboutLazyRoute = LayoutAboutLazyImport.update({
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() => import('./routes/_layout/about.lazy').then((d) => d.Route))

const LayoutTeamsRoute = LayoutTeamsImport.update({
  path: '/teams',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTeamRoute = LayoutTeamImport.update({
  path: '/team',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSeasonsRoute = LayoutSeasonsImport.update({
  path: '/seasons',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSeasonRoute = LayoutSeasonImport.update({
  path: '/season',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSearchRoute = LayoutSearchImport.update({
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMaratonRoute = LayoutMaratonImport.update({
  path: '/maraton',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardRoute = LayoutDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTeamsIndexRoute = LayoutTeamsIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutTeamsRoute,
} as any)

const LayoutSearchIndexRoute = LayoutSearchIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutSearchRoute,
} as any)

const LayoutDashboardIndexRoute = LayoutDashboardIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutDashboardRoute,
} as any)

const LayoutTeamsMapLazyRoute = LayoutTeamsMapLazyImport.update({
  path: '/map',
  getParentRoute: () => LayoutTeamsRoute,
} as any).lazy(() =>
  import('./routes/_layout/teams/map.lazy').then((d) => d.Route),
)

const LayoutTeamsSelectionRoute = LayoutTeamsSelectionImport.update({
  path: '/selection',
  getParentRoute: () => LayoutTeamsRoute,
} as any)

const LayoutTeamsCompareRoute = LayoutTeamsCompareImport.update({
  path: '/compare',
  getParentRoute: () => LayoutTeamsRoute,
} as any)

const LayoutTeamTeamIdRoute = LayoutTeamTeamIdImport.update({
  path: '/$teamId',
  getParentRoute: () => LayoutTeamRoute,
} as any)

const LayoutSeasonSeasonIdRoute = LayoutSeasonSeasonIdImport.update({
  path: '/$seasonId',
  getParentRoute: () => LayoutSeasonRoute,
} as any)

const LayoutSearchHelpRoute = LayoutSearchHelpImport.update({
  path: '/help',
  getParentRoute: () => LayoutSearchRoute,
} as any)

const LayoutMaratonTableRoute = LayoutMaratonTableImport.update({
  path: '/table',
  getParentRoute: () => LayoutMaratonRoute,
} as any)

const LayoutMaratonRecordsRoute = LayoutMaratonRecordsImport.update({
  path: '/records',
  getParentRoute: () => LayoutMaratonRoute,
} as any)

const LayoutMaratonHelpRoute = LayoutMaratonHelpImport.update({
  path: '/help',
  getParentRoute: () => LayoutMaratonRoute,
} as any)

const LayoutDashboardSeasonsRoute = LayoutDashboardSeasonsImport.update({
  path: '/seasons',
  getParentRoute: () => LayoutDashboardRoute,
} as any)

const LayoutDashboardNewSeasonRoute = LayoutDashboardNewSeasonImport.update({
  path: '/newSeason',
  getParentRoute: () => LayoutDashboardRoute,
} as any)

const LayoutDashboardErrorsRoute = LayoutDashboardErrorsImport.update({
  path: '/errors',
  getParentRoute: () => LayoutDashboardRoute,
} as any)

const LayoutDashboardAddTeamsRoute = LayoutDashboardAddTeamsImport.update({
  path: '/addTeams',
  getParentRoute: () => LayoutDashboardRoute,
} as any)

const LayoutMaratonRecordsIndexRoute = LayoutMaratonRecordsIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutMaratonRecordsRoute,
} as any)

const LayoutSeasonSeasonIdStatsRoute = LayoutSeasonSeasonIdStatsImport.update({
  path: '/stats',
  getParentRoute: () => LayoutSeasonSeasonIdRoute,
} as any)

const LayoutSeasonSeasonIdPlayoffRoute =
  LayoutSeasonSeasonIdPlayoffImport.update({
    path: '/playoff',
    getParentRoute: () => LayoutSeasonSeasonIdRoute,
  } as any)

const LayoutSeasonSeasonIdMapRoute = LayoutSeasonSeasonIdMapImport.update({
  path: '/map',
  getParentRoute: () => LayoutSeasonSeasonIdRoute,
} as any)

const LayoutSeasonSeasonIdGamesRoute = LayoutSeasonSeasonIdGamesImport.update({
  path: '/games',
  getParentRoute: () => LayoutSeasonSeasonIdRoute,
} as any)

const LayoutSeasonSeasonIdDevelopmentRoute =
  LayoutSeasonSeasonIdDevelopmentImport.update({
    path: '/development',
    getParentRoute: () => LayoutSeasonSeasonIdRoute,
  } as any)

const LayoutMaratonTableTableRoute = LayoutMaratonTableTableImport.update({
  path: '/$table',
  getParentRoute: () => LayoutMaratonTableRoute,
} as any)

const LayoutMaratonRecordsStreaksRoute =
  LayoutMaratonRecordsStreaksImport.update({
    path: '/streaks',
    getParentRoute: () => LayoutMaratonRecordsRoute,
  } as any)

const LayoutMaratonRecordsScoredRoute = LayoutMaratonRecordsScoredImport.update(
  {
    path: '/scored',
    getParentRoute: () => LayoutMaratonRecordsRoute,
  } as any,
)

const LayoutMaratonRecordsPointsRoute = LayoutMaratonRecordsPointsImport.update(
  {
    path: '/points',
    getParentRoute: () => LayoutMaratonRecordsRoute,
  } as any,
)

const LayoutMaratonRecordsConcededRoute =
  LayoutMaratonRecordsConcededImport.update({
    path: '/conceded',
    getParentRoute: () => LayoutMaratonRecordsRoute,
  } as any)

const LayoutDashboardSeasonSeasonIdRoute =
  LayoutDashboardSeasonSeasonIdImport.update({
    path: '/season/$seasonId',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)

const LayoutSeasonSeasonIdTablesIndexRoute =
  LayoutSeasonSeasonIdTablesIndexImport.update({
    path: '/tables/',
    getParentRoute: () => LayoutSeasonSeasonIdRoute,
  } as any)

const LayoutDashboardSeasonSeasonIdIndexRoute =
  LayoutDashboardSeasonSeasonIdIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)

const LayoutDashboardSeasonSeasonIdTeamseasonRoute =
  LayoutDashboardSeasonSeasonIdTeamseasonImport.update({
    path: '/teamseason',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)

const LayoutDashboardSeasonSeasonIdNewseriesRoute =
  LayoutDashboardSeasonSeasonIdNewseriesImport.update({
    path: '/newseries',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)

const LayoutDashboardSeasonSeasonIdMetadataRoute =
  LayoutDashboardSeasonSeasonIdMetadataImport.update({
    path: '/metadata',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)

const LayoutDashboardSeasonSeasonIdBulkgamesRoute =
  LayoutDashboardSeasonSeasonIdBulkgamesImport.update({
    path: '/bulkgames',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)

const LayoutSeasonSeasonIdTablesTableTableRoute =
  LayoutSeasonSeasonIdTablesTableTableImport.update({
    path: '/tables/$table',
    getParentRoute: () => LayoutSeasonSeasonIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/maraton': {
      id: '/_layout/maraton'
      path: '/maraton'
      fullPath: '/maraton'
      preLoaderRoute: typeof LayoutMaratonImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/season': {
      id: '/_layout/season'
      path: '/season'
      fullPath: '/season'
      preLoaderRoute: typeof LayoutSeasonImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/seasons': {
      id: '/_layout/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof LayoutSeasonsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/team': {
      id: '/_layout/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof LayoutTeamImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/teams': {
      id: '/_layout/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof LayoutTeamsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/unauthorized': {
      id: '/_layout/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof LayoutUnauthorizedLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/addTeams': {
      id: '/_layout/dashboard/addTeams'
      path: '/addTeams'
      fullPath: '/dashboard/addTeams'
      preLoaderRoute: typeof LayoutDashboardAddTeamsImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout/dashboard/errors': {
      id: '/_layout/dashboard/errors'
      path: '/errors'
      fullPath: '/dashboard/errors'
      preLoaderRoute: typeof LayoutDashboardErrorsImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout/dashboard/newSeason': {
      id: '/_layout/dashboard/newSeason'
      path: '/newSeason'
      fullPath: '/dashboard/newSeason'
      preLoaderRoute: typeof LayoutDashboardNewSeasonImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout/dashboard/seasons': {
      id: '/_layout/dashboard/seasons'
      path: '/seasons'
      fullPath: '/dashboard/seasons'
      preLoaderRoute: typeof LayoutDashboardSeasonsImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout/maraton/help': {
      id: '/_layout/maraton/help'
      path: '/help'
      fullPath: '/maraton/help'
      preLoaderRoute: typeof LayoutMaratonHelpImport
      parentRoute: typeof LayoutMaratonImport
    }
    '/_layout/maraton/records': {
      id: '/_layout/maraton/records'
      path: '/records'
      fullPath: '/maraton/records'
      preLoaderRoute: typeof LayoutMaratonRecordsImport
      parentRoute: typeof LayoutMaratonImport
    }
    '/_layout/maraton/table': {
      id: '/_layout/maraton/table'
      path: '/table'
      fullPath: '/maraton/table'
      preLoaderRoute: typeof LayoutMaratonTableImport
      parentRoute: typeof LayoutMaratonImport
    }
    '/_layout/search/help': {
      id: '/_layout/search/help'
      path: '/help'
      fullPath: '/search/help'
      preLoaderRoute: typeof LayoutSearchHelpImport
      parentRoute: typeof LayoutSearchImport
    }
    '/_layout/season/$seasonId': {
      id: '/_layout/season/$seasonId'
      path: '/$seasonId'
      fullPath: '/season/$seasonId'
      preLoaderRoute: typeof LayoutSeasonSeasonIdImport
      parentRoute: typeof LayoutSeasonImport
    }
    '/_layout/team/$teamId': {
      id: '/_layout/team/$teamId'
      path: '/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof LayoutTeamTeamIdImport
      parentRoute: typeof LayoutTeamImport
    }
    '/_layout/teams/compare': {
      id: '/_layout/teams/compare'
      path: '/compare'
      fullPath: '/teams/compare'
      preLoaderRoute: typeof LayoutTeamsCompareImport
      parentRoute: typeof LayoutTeamsImport
    }
    '/_layout/teams/selection': {
      id: '/_layout/teams/selection'
      path: '/selection'
      fullPath: '/teams/selection'
      preLoaderRoute: typeof LayoutTeamsSelectionImport
      parentRoute: typeof LayoutTeamsImport
    }
    '/_layout/teams/map': {
      id: '/_layout/teams/map'
      path: '/map'
      fullPath: '/teams/map'
      preLoaderRoute: typeof LayoutTeamsMapLazyImport
      parentRoute: typeof LayoutTeamsImport
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutDashboardIndexImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout/search/': {
      id: '/_layout/search/'
      path: '/'
      fullPath: '/search/'
      preLoaderRoute: typeof LayoutSearchIndexImport
      parentRoute: typeof LayoutSearchImport
    }
    '/_layout/teams/': {
      id: '/_layout/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof LayoutTeamsIndexImport
      parentRoute: typeof LayoutTeamsImport
    }
    '/_layout/dashboard/season/$seasonId': {
      id: '/_layout/dashboard/season/$seasonId'
      path: '/season/$seasonId'
      fullPath: '/dashboard/season/$seasonId'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout/maraton/records/conceded': {
      id: '/_layout/maraton/records/conceded'
      path: '/conceded'
      fullPath: '/maraton/records/conceded'
      preLoaderRoute: typeof LayoutMaratonRecordsConcededImport
      parentRoute: typeof LayoutMaratonRecordsImport
    }
    '/_layout/maraton/records/points': {
      id: '/_layout/maraton/records/points'
      path: '/points'
      fullPath: '/maraton/records/points'
      preLoaderRoute: typeof LayoutMaratonRecordsPointsImport
      parentRoute: typeof LayoutMaratonRecordsImport
    }
    '/_layout/maraton/records/scored': {
      id: '/_layout/maraton/records/scored'
      path: '/scored'
      fullPath: '/maraton/records/scored'
      preLoaderRoute: typeof LayoutMaratonRecordsScoredImport
      parentRoute: typeof LayoutMaratonRecordsImport
    }
    '/_layout/maraton/records/streaks': {
      id: '/_layout/maraton/records/streaks'
      path: '/streaks'
      fullPath: '/maraton/records/streaks'
      preLoaderRoute: typeof LayoutMaratonRecordsStreaksImport
      parentRoute: typeof LayoutMaratonRecordsImport
    }
    '/_layout/maraton/table/$table': {
      id: '/_layout/maraton/table/$table'
      path: '/$table'
      fullPath: '/maraton/table/$table'
      preLoaderRoute: typeof LayoutMaratonTableTableImport
      parentRoute: typeof LayoutMaratonTableImport
    }
    '/_layout/season/$seasonId/development': {
      id: '/_layout/season/$seasonId/development'
      path: '/development'
      fullPath: '/season/$seasonId/development'
      preLoaderRoute: typeof LayoutSeasonSeasonIdDevelopmentImport
      parentRoute: typeof LayoutSeasonSeasonIdImport
    }
    '/_layout/season/$seasonId/games': {
      id: '/_layout/season/$seasonId/games'
      path: '/games'
      fullPath: '/season/$seasonId/games'
      preLoaderRoute: typeof LayoutSeasonSeasonIdGamesImport
      parentRoute: typeof LayoutSeasonSeasonIdImport
    }
    '/_layout/season/$seasonId/map': {
      id: '/_layout/season/$seasonId/map'
      path: '/map'
      fullPath: '/season/$seasonId/map'
      preLoaderRoute: typeof LayoutSeasonSeasonIdMapImport
      parentRoute: typeof LayoutSeasonSeasonIdImport
    }
    '/_layout/season/$seasonId/playoff': {
      id: '/_layout/season/$seasonId/playoff'
      path: '/playoff'
      fullPath: '/season/$seasonId/playoff'
      preLoaderRoute: typeof LayoutSeasonSeasonIdPlayoffImport
      parentRoute: typeof LayoutSeasonSeasonIdImport
    }
    '/_layout/season/$seasonId/stats': {
      id: '/_layout/season/$seasonId/stats'
      path: '/stats'
      fullPath: '/season/$seasonId/stats'
      preLoaderRoute: typeof LayoutSeasonSeasonIdStatsImport
      parentRoute: typeof LayoutSeasonSeasonIdImport
    }
    '/_layout/maraton/records/': {
      id: '/_layout/maraton/records/'
      path: '/'
      fullPath: '/maraton/records/'
      preLoaderRoute: typeof LayoutMaratonRecordsIndexImport
      parentRoute: typeof LayoutMaratonRecordsImport
    }
    '/_layout/dashboard/season/$seasonId/bulkgames': {
      id: '/_layout/dashboard/season/$seasonId/bulkgames'
      path: '/bulkgames'
      fullPath: '/dashboard/season/$seasonId/bulkgames'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdBulkgamesImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdImport
    }
    '/_layout/dashboard/season/$seasonId/metadata': {
      id: '/_layout/dashboard/season/$seasonId/metadata'
      path: '/metadata'
      fullPath: '/dashboard/season/$seasonId/metadata'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdMetadataImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdImport
    }
    '/_layout/dashboard/season/$seasonId/newseries': {
      id: '/_layout/dashboard/season/$seasonId/newseries'
      path: '/newseries'
      fullPath: '/dashboard/season/$seasonId/newseries'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdNewseriesImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdImport
    }
    '/_layout/dashboard/season/$seasonId/teamseason': {
      id: '/_layout/dashboard/season/$seasonId/teamseason'
      path: '/teamseason'
      fullPath: '/dashboard/season/$seasonId/teamseason'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdTeamseasonImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdImport
    }
    '/_layout/dashboard/season/$seasonId/': {
      id: '/_layout/dashboard/season/$seasonId/'
      path: '/'
      fullPath: '/dashboard/season/$seasonId/'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdIndexImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdImport
    }
    '/_layout/season/$seasonId/tables/': {
      id: '/_layout/season/$seasonId/tables/'
      path: '/tables'
      fullPath: '/season/$seasonId/tables'
      preLoaderRoute: typeof LayoutSeasonSeasonIdTablesIndexImport
      parentRoute: typeof LayoutSeasonSeasonIdImport
    }
    '/_layout/season/$seasonId/tables/_table/$table': {
      id: '/_layout/season/$seasonId/tables/_table/$table'
      path: '/tables/$table'
      fullPath: '/season/$seasonId/tables/$table'
      preLoaderRoute: typeof LayoutSeasonSeasonIdTablesTableTableImport
      parentRoute: typeof LayoutSeasonSeasonIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutDashboardRoute: LayoutDashboardRoute.addChildren({
      LayoutDashboardAddTeamsRoute,
      LayoutDashboardErrorsRoute,
      LayoutDashboardNewSeasonRoute,
      LayoutDashboardSeasonsRoute,
      LayoutDashboardIndexRoute,
      LayoutDashboardSeasonSeasonIdRoute:
        LayoutDashboardSeasonSeasonIdRoute.addChildren({
          LayoutDashboardSeasonSeasonIdBulkgamesRoute,
          LayoutDashboardSeasonSeasonIdMetadataRoute,
          LayoutDashboardSeasonSeasonIdNewseriesRoute,
          LayoutDashboardSeasonSeasonIdTeamseasonRoute,
          LayoutDashboardSeasonSeasonIdIndexRoute,
        }),
    }),
    LayoutMaratonRoute: LayoutMaratonRoute.addChildren({
      LayoutMaratonHelpRoute,
      LayoutMaratonRecordsRoute: LayoutMaratonRecordsRoute.addChildren({
        LayoutMaratonRecordsConcededRoute,
        LayoutMaratonRecordsPointsRoute,
        LayoutMaratonRecordsScoredRoute,
        LayoutMaratonRecordsStreaksRoute,
        LayoutMaratonRecordsIndexRoute,
      }),
      LayoutMaratonTableRoute: LayoutMaratonTableRoute.addChildren({
        LayoutMaratonTableTableRoute,
      }),
    }),
    LayoutSearchRoute: LayoutSearchRoute.addChildren({
      LayoutSearchHelpRoute,
      LayoutSearchIndexRoute,
    }),
    LayoutSeasonRoute: LayoutSeasonRoute.addChildren({
      LayoutSeasonSeasonIdRoute: LayoutSeasonSeasonIdRoute.addChildren({
        LayoutSeasonSeasonIdDevelopmentRoute,
        LayoutSeasonSeasonIdGamesRoute,
        LayoutSeasonSeasonIdMapRoute,
        LayoutSeasonSeasonIdPlayoffRoute,
        LayoutSeasonSeasonIdStatsRoute,
        LayoutSeasonSeasonIdTablesIndexRoute,
        LayoutSeasonSeasonIdTablesTableTableRoute,
      }),
    }),
    LayoutSeasonsRoute,
    LayoutTeamRoute: LayoutTeamRoute.addChildren({ LayoutTeamTeamIdRoute }),
    LayoutTeamsRoute: LayoutTeamsRoute.addChildren({
      LayoutTeamsCompareRoute,
      LayoutTeamsSelectionRoute,
      LayoutTeamsMapLazyRoute,
      LayoutTeamsIndexRoute,
    }),
    LayoutAboutLazyRoute,
    LayoutUnauthorizedLazyRoute,
    LayoutIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/dashboard",
        "/_layout/maraton",
        "/_layout/search",
        "/_layout/season",
        "/_layout/seasons",
        "/_layout/team",
        "/_layout/teams",
        "/_layout/about",
        "/_layout/unauthorized",
        "/_layout/"
      ]
    },
    "/_layout/dashboard": {
      "filePath": "_layout/dashboard.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/dashboard/addTeams",
        "/_layout/dashboard/errors",
        "/_layout/dashboard/newSeason",
        "/_layout/dashboard/seasons",
        "/_layout/dashboard/",
        "/_layout/dashboard/season/$seasonId"
      ]
    },
    "/_layout/maraton": {
      "filePath": "_layout/maraton.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/maraton/help",
        "/_layout/maraton/records",
        "/_layout/maraton/table"
      ]
    },
    "/_layout/search": {
      "filePath": "_layout/search.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/search/help",
        "/_layout/search/"
      ]
    },
    "/_layout/season": {
      "filePath": "_layout/season.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/season/$seasonId"
      ]
    },
    "/_layout/seasons": {
      "filePath": "_layout/seasons.tsx",
      "parent": "/_layout"
    },
    "/_layout/team": {
      "filePath": "_layout/team.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/team/$teamId"
      ]
    },
    "/_layout/teams": {
      "filePath": "_layout/teams.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/teams/compare",
        "/_layout/teams/selection",
        "/_layout/teams/map",
        "/_layout/teams/"
      ]
    },
    "/_layout/about": {
      "filePath": "_layout/about.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/unauthorized": {
      "filePath": "_layout/unauthorized.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/addTeams": {
      "filePath": "_layout/dashboard/addTeams.tsx",
      "parent": "/_layout/dashboard"
    },
    "/_layout/dashboard/errors": {
      "filePath": "_layout/dashboard/errors.tsx",
      "parent": "/_layout/dashboard"
    },
    "/_layout/dashboard/newSeason": {
      "filePath": "_layout/dashboard/newSeason.tsx",
      "parent": "/_layout/dashboard"
    },
    "/_layout/dashboard/seasons": {
      "filePath": "_layout/dashboard/seasons.tsx",
      "parent": "/_layout/dashboard"
    },
    "/_layout/maraton/help": {
      "filePath": "_layout/maraton/help.tsx",
      "parent": "/_layout/maraton"
    },
    "/_layout/maraton/records": {
      "filePath": "_layout/maraton/records.tsx",
      "parent": "/_layout/maraton",
      "children": [
        "/_layout/maraton/records/conceded",
        "/_layout/maraton/records/points",
        "/_layout/maraton/records/scored",
        "/_layout/maraton/records/streaks",
        "/_layout/maraton/records/"
      ]
    },
    "/_layout/maraton/table": {
      "filePath": "_layout/maraton/table.tsx",
      "parent": "/_layout/maraton",
      "children": [
        "/_layout/maraton/table/$table"
      ]
    },
    "/_layout/search/help": {
      "filePath": "_layout/search/help.tsx",
      "parent": "/_layout/search"
    },
    "/_layout/season/$seasonId": {
      "filePath": "_layout/season/$seasonId.tsx",
      "parent": "/_layout/season",
      "children": [
        "/_layout/season/$seasonId/development",
        "/_layout/season/$seasonId/games",
        "/_layout/season/$seasonId/map",
        "/_layout/season/$seasonId/playoff",
        "/_layout/season/$seasonId/stats",
        "/_layout/season/$seasonId/tables/",
        "/_layout/season/$seasonId/tables/_table/$table"
      ]
    },
    "/_layout/team/$teamId": {
      "filePath": "_layout/team/$teamId.tsx",
      "parent": "/_layout/team"
    },
    "/_layout/teams/compare": {
      "filePath": "_layout/teams/compare.tsx",
      "parent": "/_layout/teams"
    },
    "/_layout/teams/selection": {
      "filePath": "_layout/teams/selection.tsx",
      "parent": "/_layout/teams"
    },
    "/_layout/teams/map": {
      "filePath": "_layout/teams/map.lazy.tsx",
      "parent": "/_layout/teams"
    },
    "/_layout/dashboard/": {
      "filePath": "_layout/dashboard/index.tsx",
      "parent": "/_layout/dashboard"
    },
    "/_layout/search/": {
      "filePath": "_layout/search/index.tsx",
      "parent": "/_layout/search"
    },
    "/_layout/teams/": {
      "filePath": "_layout/teams/index.tsx",
      "parent": "/_layout/teams"
    },
    "/_layout/dashboard/season/$seasonId": {
      "filePath": "_layout/dashboard/season/$seasonId.tsx",
      "parent": "/_layout/dashboard",
      "children": [
        "/_layout/dashboard/season/$seasonId/bulkgames",
        "/_layout/dashboard/season/$seasonId/metadata",
        "/_layout/dashboard/season/$seasonId/newseries",
        "/_layout/dashboard/season/$seasonId/teamseason",
        "/_layout/dashboard/season/$seasonId/"
      ]
    },
    "/_layout/maraton/records/conceded": {
      "filePath": "_layout/maraton/records/conceded.tsx",
      "parent": "/_layout/maraton/records"
    },
    "/_layout/maraton/records/points": {
      "filePath": "_layout/maraton/records/points.tsx",
      "parent": "/_layout/maraton/records"
    },
    "/_layout/maraton/records/scored": {
      "filePath": "_layout/maraton/records/scored.tsx",
      "parent": "/_layout/maraton/records"
    },
    "/_layout/maraton/records/streaks": {
      "filePath": "_layout/maraton/records/streaks.tsx",
      "parent": "/_layout/maraton/records"
    },
    "/_layout/maraton/table/$table": {
      "filePath": "_layout/maraton/table/$table.tsx",
      "parent": "/_layout/maraton/table"
    },
    "/_layout/season/$seasonId/development": {
      "filePath": "_layout/season/$seasonId.development.tsx",
      "parent": "/_layout/season/$seasonId"
    },
    "/_layout/season/$seasonId/games": {
      "filePath": "_layout/season/$seasonId.games.tsx",
      "parent": "/_layout/season/$seasonId"
    },
    "/_layout/season/$seasonId/map": {
      "filePath": "_layout/season/$seasonId.map.tsx",
      "parent": "/_layout/season/$seasonId"
    },
    "/_layout/season/$seasonId/playoff": {
      "filePath": "_layout/season/$seasonId.playoff.tsx",
      "parent": "/_layout/season/$seasonId"
    },
    "/_layout/season/$seasonId/stats": {
      "filePath": "_layout/season/$seasonId.stats.tsx",
      "parent": "/_layout/season/$seasonId"
    },
    "/_layout/maraton/records/": {
      "filePath": "_layout/maraton/records/index.tsx",
      "parent": "/_layout/maraton/records"
    },
    "/_layout/dashboard/season/$seasonId/bulkgames": {
      "filePath": "_layout/dashboard/season/$seasonId.bulkgames.tsx",
      "parent": "/_layout/dashboard/season/$seasonId"
    },
    "/_layout/dashboard/season/$seasonId/metadata": {
      "filePath": "_layout/dashboard/season/$seasonId.metadata.tsx",
      "parent": "/_layout/dashboard/season/$seasonId"
    },
    "/_layout/dashboard/season/$seasonId/newseries": {
      "filePath": "_layout/dashboard/season/$seasonId.newseries.tsx",
      "parent": "/_layout/dashboard/season/$seasonId"
    },
    "/_layout/dashboard/season/$seasonId/teamseason": {
      "filePath": "_layout/dashboard/season/$seasonId.teamseason_.tsx",
      "parent": "/_layout/dashboard/season/$seasonId"
    },
    "/_layout/dashboard/season/$seasonId/": {
      "filePath": "_layout/dashboard/season/$seasonId.index.tsx",
      "parent": "/_layout/dashboard/season/$seasonId"
    },
    "/_layout/season/$seasonId/tables/": {
      "filePath": "_layout/season/$seasonId/tables/index.tsx",
      "parent": "/_layout/season/$seasonId"
    },
    "/_layout/season/$seasonId/tables/_table/$table": {
      "filePath": "_layout/season/$seasonId/tables/_table/$table.tsx",
      "parent": "/_layout/season/$seasonId"
    }
  }
}
ROUTE_MANIFEST_END */
