/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutTeamsImport } from './routes/_layout/teams'
import { Route as LayoutTeamImport } from './routes/_layout/team'
import { Route as LayoutSeasonsImport } from './routes/_layout/seasons'
import { Route as LayoutSeasonImport } from './routes/_layout/season'
import { Route as LayoutSearchImport } from './routes/_layout/search'
import { Route as LayoutMaratonImport } from './routes/_layout/maraton'
import { Route as LayoutDashboardImport } from './routes/_layout/dashboard'
import { Route as LayoutTeamsIndexImport } from './routes/_layout/teams/index'
import { Route as LayoutSearchIndexImport } from './routes/_layout/search/index'
import { Route as LayoutDashboardIndexImport } from './routes/_layout/dashboard/index'
import { Route as LayoutTeamsSelectionImport } from './routes/_layout/teams/selection'
import { Route as LayoutTeamsCompareImport } from './routes/_layout/teams/compare'
import { Route as LayoutTeamTeamIdImport } from './routes/_layout/team/$teamId'
import { Route as LayoutSeasonSeasonIdImport } from './routes/_layout/season/$seasonId'
import { Route as LayoutSearchHelpImport } from './routes/_layout/search/help'
import { Route as LayoutMaratonTableImport } from './routes/_layout/maraton/table'
import { Route as LayoutMaratonRecordsImport } from './routes/_layout/maraton/records'
import { Route as LayoutMaratonHelpImport } from './routes/_layout/maraton/help'
import { Route as LayoutDashboardSeasonsImport } from './routes/_layout/dashboard/seasons'
import { Route as LayoutDashboardNewSeasonImport } from './routes/_layout/dashboard/newSeason'
import { Route as LayoutDashboardErrorsImport } from './routes/_layout/dashboard/errors'
import { Route as LayoutDashboardAddTeamsImport } from './routes/_layout/dashboard/addTeams'
import { Route as LayoutMaratonRecordsIndexImport } from './routes/_layout/maraton/records/index'
import { Route as LayoutDashboardTeamsIndexImport } from './routes/_layout/dashboard/teams/index'
import { Route as LayoutSeasonSeasonIdStatsImport } from './routes/_layout/season/$seasonId.stats'
import { Route as LayoutSeasonSeasonIdPlayoffImport } from './routes/_layout/season/$seasonId.playoff'
import { Route as LayoutSeasonSeasonIdGamesImport } from './routes/_layout/season/$seasonId.games'
import { Route as LayoutSeasonSeasonIdDevelopmentImport } from './routes/_layout/season/$seasonId.development'
import { Route as LayoutMaratonTableTableImport } from './routes/_layout/maraton/table/$table'
import { Route as LayoutMaratonRecordsStreaksImport } from './routes/_layout/maraton/records/streaks'
import { Route as LayoutMaratonRecordsScoredImport } from './routes/_layout/maraton/records/scored'
import { Route as LayoutMaratonRecordsPointsImport } from './routes/_layout/maraton/records/points'
import { Route as LayoutMaratonRecordsConcededImport } from './routes/_layout/maraton/records/conceded'
import { Route as LayoutDashboardSeasonSeasonIdImport } from './routes/_layout/dashboard/season/$seasonId'
import { Route as LayoutSeasonSeasonIdTablesIndexImport } from './routes/_layout/season/$seasonId/tables/index'
import { Route as LayoutDashboardSeasonSeasonIdIndexImport } from './routes/_layout/dashboard/season/$seasonId/index'
import { Route as LayoutDashboardTeamsTeamIdDeleteImport } from './routes/_layout/dashboard/teams/$teamId/delete'
import { Route as LayoutDashboardSeasonSeasonIdTeamseasonIndexImport } from './routes/_layout/dashboard/season/$seasonId/teamseason_/index'
import { Route as LayoutDashboardSeasonSeasonIdNewseriesIndexImport } from './routes/_layout/dashboard/season/$seasonId/newseries/index'
import { Route as LayoutDashboardSeasonSeasonIdMetadataIndexImport } from './routes/_layout/dashboard/season/$seasonId/metadata/index'
import { Route as LayoutDashboardSeasonSeasonIdBulkgamesIndexImport } from './routes/_layout/dashboard/season/$seasonId/bulkgames/index'
import { Route as LayoutSeasonSeasonIdTablesTableTableImport } from './routes/_layout/season/$seasonId/tables/_table/$table'
import { Route as LayoutDashboardSeasonSeasonIdGamesSerieIdImport } from './routes/_layout/dashboard/season/$seasonId/games/$serieId'
import { Route as LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdImport } from './routes/_layout/dashboard/season/$seasonId/games/$serieId/$gameId'
import { Route as LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdEditImport } from './routes/_layout/dashboard/season/$seasonId/games/$serieId/$gameId/edit'
import { Route as LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdDeleteImport } from './routes/_layout/dashboard/season/$seasonId/games/$serieId/$gameId/delete'

// Create Virtual Routes

const LayoutUnauthorizedLazyImport = createFileRoute('/_layout/unauthorized')()
const LayoutAboutLazyImport = createFileRoute('/_layout/about')()
const LayoutTeamsMapLazyImport = createFileRoute('/_layout/teams/map')()
const LayoutSeasonSeasonIdMapLazyImport = createFileRoute(
  '/_layout/season/$seasonId/map',
)()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutUnauthorizedLazyRoute = LayoutUnauthorizedLazyImport.update({
  path: '/unauthorized',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/unauthorized.lazy').then((d) => d.Route),
)

const LayoutAboutLazyRoute = LayoutAboutLazyImport.update({
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() => import('./routes/_layout/about.lazy').then((d) => d.Route))

const LayoutTeamsRoute = LayoutTeamsImport.update({
  path: '/teams',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTeamRoute = LayoutTeamImport.update({
  path: '/team',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSeasonsRoute = LayoutSeasonsImport.update({
  path: '/seasons',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSeasonRoute = LayoutSeasonImport.update({
  path: '/season',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSearchRoute = LayoutSearchImport.update({
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMaratonRoute = LayoutMaratonImport.update({
  path: '/maraton',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardRoute = LayoutDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTeamsIndexRoute = LayoutTeamsIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutTeamsRoute,
} as any)

const LayoutSearchIndexRoute = LayoutSearchIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutSearchRoute,
} as any)

const LayoutDashboardIndexRoute = LayoutDashboardIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutDashboardRoute,
} as any)

const LayoutTeamsMapLazyRoute = LayoutTeamsMapLazyImport.update({
  path: '/map',
  getParentRoute: () => LayoutTeamsRoute,
} as any).lazy(() =>
  import('./routes/_layout/teams/map.lazy').then((d) => d.Route),
)

const LayoutTeamsSelectionRoute = LayoutTeamsSelectionImport.update({
  path: '/selection',
  getParentRoute: () => LayoutTeamsRoute,
} as any)

const LayoutTeamsCompareRoute = LayoutTeamsCompareImport.update({
  path: '/compare',
  getParentRoute: () => LayoutTeamsRoute,
} as any)

const LayoutTeamTeamIdRoute = LayoutTeamTeamIdImport.update({
  path: '/$teamId',
  getParentRoute: () => LayoutTeamRoute,
} as any)

const LayoutSeasonSeasonIdRoute = LayoutSeasonSeasonIdImport.update({
  path: '/$seasonId',
  getParentRoute: () => LayoutSeasonRoute,
} as any)

const LayoutSearchHelpRoute = LayoutSearchHelpImport.update({
  path: '/help',
  getParentRoute: () => LayoutSearchRoute,
} as any)

const LayoutMaratonTableRoute = LayoutMaratonTableImport.update({
  path: '/table',
  getParentRoute: () => LayoutMaratonRoute,
} as any)

const LayoutMaratonRecordsRoute = LayoutMaratonRecordsImport.update({
  path: '/records',
  getParentRoute: () => LayoutMaratonRoute,
} as any)

const LayoutMaratonHelpRoute = LayoutMaratonHelpImport.update({
  path: '/help',
  getParentRoute: () => LayoutMaratonRoute,
} as any)

const LayoutDashboardSeasonsRoute = LayoutDashboardSeasonsImport.update({
  path: '/seasons',
  getParentRoute: () => LayoutDashboardRoute,
} as any)

const LayoutDashboardNewSeasonRoute = LayoutDashboardNewSeasonImport.update({
  path: '/newSeason',
  getParentRoute: () => LayoutDashboardRoute,
} as any)

const LayoutDashboardErrorsRoute = LayoutDashboardErrorsImport.update({
  path: '/errors',
  getParentRoute: () => LayoutDashboardRoute,
} as any)

const LayoutDashboardAddTeamsRoute = LayoutDashboardAddTeamsImport.update({
  path: '/addTeams',
  getParentRoute: () => LayoutDashboardRoute,
} as any)

const LayoutMaratonRecordsIndexRoute = LayoutMaratonRecordsIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutMaratonRecordsRoute,
} as any)

const LayoutDashboardTeamsIndexRoute = LayoutDashboardTeamsIndexImport.update({
  path: '/teams/',
  getParentRoute: () => LayoutDashboardRoute,
} as any)

const LayoutSeasonSeasonIdMapLazyRoute =
  LayoutSeasonSeasonIdMapLazyImport.update({
    path: '/map',
    getParentRoute: () => LayoutSeasonSeasonIdRoute,
  } as any).lazy(() =>
    import('./routes/_layout/season/$seasonId.map.lazy').then((d) => d.Route),
  )

const LayoutSeasonSeasonIdStatsRoute = LayoutSeasonSeasonIdStatsImport.update({
  path: '/stats',
  getParentRoute: () => LayoutSeasonSeasonIdRoute,
} as any)

const LayoutSeasonSeasonIdPlayoffRoute =
  LayoutSeasonSeasonIdPlayoffImport.update({
    path: '/playoff',
    getParentRoute: () => LayoutSeasonSeasonIdRoute,
  } as any)

const LayoutSeasonSeasonIdGamesRoute = LayoutSeasonSeasonIdGamesImport.update({
  path: '/games',
  getParentRoute: () => LayoutSeasonSeasonIdRoute,
} as any)

const LayoutSeasonSeasonIdDevelopmentRoute =
  LayoutSeasonSeasonIdDevelopmentImport.update({
    path: '/development',
    getParentRoute: () => LayoutSeasonSeasonIdRoute,
  } as any)

const LayoutMaratonTableTableRoute = LayoutMaratonTableTableImport.update({
  path: '/$table',
  getParentRoute: () => LayoutMaratonTableRoute,
} as any)

const LayoutMaratonRecordsStreaksRoute =
  LayoutMaratonRecordsStreaksImport.update({
    path: '/streaks',
    getParentRoute: () => LayoutMaratonRecordsRoute,
  } as any)

const LayoutMaratonRecordsScoredRoute = LayoutMaratonRecordsScoredImport.update(
  {
    path: '/scored',
    getParentRoute: () => LayoutMaratonRecordsRoute,
  } as any,
)

const LayoutMaratonRecordsPointsRoute = LayoutMaratonRecordsPointsImport.update(
  {
    path: '/points',
    getParentRoute: () => LayoutMaratonRecordsRoute,
  } as any,
)

const LayoutMaratonRecordsConcededRoute =
  LayoutMaratonRecordsConcededImport.update({
    path: '/conceded',
    getParentRoute: () => LayoutMaratonRecordsRoute,
  } as any)

const LayoutDashboardSeasonSeasonIdRoute =
  LayoutDashboardSeasonSeasonIdImport.update({
    path: '/season/$seasonId',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)

const LayoutSeasonSeasonIdTablesIndexRoute =
  LayoutSeasonSeasonIdTablesIndexImport.update({
    path: '/tables/',
    getParentRoute: () => LayoutSeasonSeasonIdRoute,
  } as any)

const LayoutDashboardSeasonSeasonIdIndexRoute =
  LayoutDashboardSeasonSeasonIdIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)

const LayoutDashboardTeamsTeamIdDeleteRoute =
  LayoutDashboardTeamsTeamIdDeleteImport.update({
    path: '/teams/$teamId/delete',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)

const LayoutDashboardSeasonSeasonIdTeamseasonIndexRoute =
  LayoutDashboardSeasonSeasonIdTeamseasonIndexImport.update({
    path: '/teamseason/',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)

const LayoutDashboardSeasonSeasonIdNewseriesIndexRoute =
  LayoutDashboardSeasonSeasonIdNewseriesIndexImport.update({
    path: '/newseries/',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)

const LayoutDashboardSeasonSeasonIdMetadataIndexRoute =
  LayoutDashboardSeasonSeasonIdMetadataIndexImport.update({
    path: '/metadata/',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)

const LayoutDashboardSeasonSeasonIdBulkgamesIndexRoute =
  LayoutDashboardSeasonSeasonIdBulkgamesIndexImport.update({
    path: '/bulkgames/',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)

const LayoutSeasonSeasonIdTablesTableTableRoute =
  LayoutSeasonSeasonIdTablesTableTableImport.update({
    path: '/tables/$table',
    getParentRoute: () => LayoutSeasonSeasonIdRoute,
  } as any)

const LayoutDashboardSeasonSeasonIdGamesSerieIdRoute =
  LayoutDashboardSeasonSeasonIdGamesSerieIdImport.update({
    path: '/games/$serieId',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)

const LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdRoute =
  LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdImport.update({
    path: '/$gameId',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdGamesSerieIdRoute,
  } as any)

const LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdEditRoute =
  LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdEditImport.update({
    path: '/edit',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdRoute,
  } as any)

const LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdDeleteRoute =
  LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdDeleteImport.update({
    path: '/delete',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/maraton': {
      id: '/_layout/maraton'
      path: '/maraton'
      fullPath: '/maraton'
      preLoaderRoute: typeof LayoutMaratonImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/season': {
      id: '/_layout/season'
      path: '/season'
      fullPath: '/season'
      preLoaderRoute: typeof LayoutSeasonImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/seasons': {
      id: '/_layout/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof LayoutSeasonsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/team': {
      id: '/_layout/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof LayoutTeamImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/teams': {
      id: '/_layout/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof LayoutTeamsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/unauthorized': {
      id: '/_layout/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof LayoutUnauthorizedLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/addTeams': {
      id: '/_layout/dashboard/addTeams'
      path: '/addTeams'
      fullPath: '/dashboard/addTeams'
      preLoaderRoute: typeof LayoutDashboardAddTeamsImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout/dashboard/errors': {
      id: '/_layout/dashboard/errors'
      path: '/errors'
      fullPath: '/dashboard/errors'
      preLoaderRoute: typeof LayoutDashboardErrorsImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout/dashboard/newSeason': {
      id: '/_layout/dashboard/newSeason'
      path: '/newSeason'
      fullPath: '/dashboard/newSeason'
      preLoaderRoute: typeof LayoutDashboardNewSeasonImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout/dashboard/seasons': {
      id: '/_layout/dashboard/seasons'
      path: '/seasons'
      fullPath: '/dashboard/seasons'
      preLoaderRoute: typeof LayoutDashboardSeasonsImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout/maraton/help': {
      id: '/_layout/maraton/help'
      path: '/help'
      fullPath: '/maraton/help'
      preLoaderRoute: typeof LayoutMaratonHelpImport
      parentRoute: typeof LayoutMaratonImport
    }
    '/_layout/maraton/records': {
      id: '/_layout/maraton/records'
      path: '/records'
      fullPath: '/maraton/records'
      preLoaderRoute: typeof LayoutMaratonRecordsImport
      parentRoute: typeof LayoutMaratonImport
    }
    '/_layout/maraton/table': {
      id: '/_layout/maraton/table'
      path: '/table'
      fullPath: '/maraton/table'
      preLoaderRoute: typeof LayoutMaratonTableImport
      parentRoute: typeof LayoutMaratonImport
    }
    '/_layout/search/help': {
      id: '/_layout/search/help'
      path: '/help'
      fullPath: '/search/help'
      preLoaderRoute: typeof LayoutSearchHelpImport
      parentRoute: typeof LayoutSearchImport
    }
    '/_layout/season/$seasonId': {
      id: '/_layout/season/$seasonId'
      path: '/$seasonId'
      fullPath: '/season/$seasonId'
      preLoaderRoute: typeof LayoutSeasonSeasonIdImport
      parentRoute: typeof LayoutSeasonImport
    }
    '/_layout/team/$teamId': {
      id: '/_layout/team/$teamId'
      path: '/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof LayoutTeamTeamIdImport
      parentRoute: typeof LayoutTeamImport
    }
    '/_layout/teams/compare': {
      id: '/_layout/teams/compare'
      path: '/compare'
      fullPath: '/teams/compare'
      preLoaderRoute: typeof LayoutTeamsCompareImport
      parentRoute: typeof LayoutTeamsImport
    }
    '/_layout/teams/selection': {
      id: '/_layout/teams/selection'
      path: '/selection'
      fullPath: '/teams/selection'
      preLoaderRoute: typeof LayoutTeamsSelectionImport
      parentRoute: typeof LayoutTeamsImport
    }
    '/_layout/teams/map': {
      id: '/_layout/teams/map'
      path: '/map'
      fullPath: '/teams/map'
      preLoaderRoute: typeof LayoutTeamsMapLazyImport
      parentRoute: typeof LayoutTeamsImport
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutDashboardIndexImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout/search/': {
      id: '/_layout/search/'
      path: '/'
      fullPath: '/search/'
      preLoaderRoute: typeof LayoutSearchIndexImport
      parentRoute: typeof LayoutSearchImport
    }
    '/_layout/teams/': {
      id: '/_layout/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof LayoutTeamsIndexImport
      parentRoute: typeof LayoutTeamsImport
    }
    '/_layout/dashboard/season/$seasonId': {
      id: '/_layout/dashboard/season/$seasonId'
      path: '/season/$seasonId'
      fullPath: '/dashboard/season/$seasonId'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout/maraton/records/conceded': {
      id: '/_layout/maraton/records/conceded'
      path: '/conceded'
      fullPath: '/maraton/records/conceded'
      preLoaderRoute: typeof LayoutMaratonRecordsConcededImport
      parentRoute: typeof LayoutMaratonRecordsImport
    }
    '/_layout/maraton/records/points': {
      id: '/_layout/maraton/records/points'
      path: '/points'
      fullPath: '/maraton/records/points'
      preLoaderRoute: typeof LayoutMaratonRecordsPointsImport
      parentRoute: typeof LayoutMaratonRecordsImport
    }
    '/_layout/maraton/records/scored': {
      id: '/_layout/maraton/records/scored'
      path: '/scored'
      fullPath: '/maraton/records/scored'
      preLoaderRoute: typeof LayoutMaratonRecordsScoredImport
      parentRoute: typeof LayoutMaratonRecordsImport
    }
    '/_layout/maraton/records/streaks': {
      id: '/_layout/maraton/records/streaks'
      path: '/streaks'
      fullPath: '/maraton/records/streaks'
      preLoaderRoute: typeof LayoutMaratonRecordsStreaksImport
      parentRoute: typeof LayoutMaratonRecordsImport
    }
    '/_layout/maraton/table/$table': {
      id: '/_layout/maraton/table/$table'
      path: '/$table'
      fullPath: '/maraton/table/$table'
      preLoaderRoute: typeof LayoutMaratonTableTableImport
      parentRoute: typeof LayoutMaratonTableImport
    }
    '/_layout/season/$seasonId/development': {
      id: '/_layout/season/$seasonId/development'
      path: '/development'
      fullPath: '/season/$seasonId/development'
      preLoaderRoute: typeof LayoutSeasonSeasonIdDevelopmentImport
      parentRoute: typeof LayoutSeasonSeasonIdImport
    }
    '/_layout/season/$seasonId/games': {
      id: '/_layout/season/$seasonId/games'
      path: '/games'
      fullPath: '/season/$seasonId/games'
      preLoaderRoute: typeof LayoutSeasonSeasonIdGamesImport
      parentRoute: typeof LayoutSeasonSeasonIdImport
    }
    '/_layout/season/$seasonId/playoff': {
      id: '/_layout/season/$seasonId/playoff'
      path: '/playoff'
      fullPath: '/season/$seasonId/playoff'
      preLoaderRoute: typeof LayoutSeasonSeasonIdPlayoffImport
      parentRoute: typeof LayoutSeasonSeasonIdImport
    }
    '/_layout/season/$seasonId/stats': {
      id: '/_layout/season/$seasonId/stats'
      path: '/stats'
      fullPath: '/season/$seasonId/stats'
      preLoaderRoute: typeof LayoutSeasonSeasonIdStatsImport
      parentRoute: typeof LayoutSeasonSeasonIdImport
    }
    '/_layout/season/$seasonId/map': {
      id: '/_layout/season/$seasonId/map'
      path: '/map'
      fullPath: '/season/$seasonId/map'
      preLoaderRoute: typeof LayoutSeasonSeasonIdMapLazyImport
      parentRoute: typeof LayoutSeasonSeasonIdImport
    }
    '/_layout/dashboard/teams/': {
      id: '/_layout/dashboard/teams/'
      path: '/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof LayoutDashboardTeamsIndexImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout/maraton/records/': {
      id: '/_layout/maraton/records/'
      path: '/'
      fullPath: '/maraton/records/'
      preLoaderRoute: typeof LayoutMaratonRecordsIndexImport
      parentRoute: typeof LayoutMaratonRecordsImport
    }
    '/_layout/dashboard/teams/$teamId/delete': {
      id: '/_layout/dashboard/teams/$teamId/delete'
      path: '/teams/$teamId/delete'
      fullPath: '/dashboard/teams/$teamId/delete'
      preLoaderRoute: typeof LayoutDashboardTeamsTeamIdDeleteImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout/dashboard/season/$seasonId/': {
      id: '/_layout/dashboard/season/$seasonId/'
      path: '/'
      fullPath: '/dashboard/season/$seasonId/'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdIndexImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdImport
    }
    '/_layout/season/$seasonId/tables/': {
      id: '/_layout/season/$seasonId/tables/'
      path: '/tables'
      fullPath: '/season/$seasonId/tables'
      preLoaderRoute: typeof LayoutSeasonSeasonIdTablesIndexImport
      parentRoute: typeof LayoutSeasonSeasonIdImport
    }
    '/_layout/dashboard/season/$seasonId/games/$serieId': {
      id: '/_layout/dashboard/season/$seasonId/games/$serieId'
      path: '/games/$serieId'
      fullPath: '/dashboard/season/$seasonId/games/$serieId'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdGamesSerieIdImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdImport
    }
    '/_layout/season/$seasonId/tables/_table/$table': {
      id: '/_layout/season/$seasonId/tables/_table/$table'
      path: '/tables/$table'
      fullPath: '/season/$seasonId/tables/$table'
      preLoaderRoute: typeof LayoutSeasonSeasonIdTablesTableTableImport
      parentRoute: typeof LayoutSeasonSeasonIdImport
    }
    '/_layout/dashboard/season/$seasonId/bulkgames/': {
      id: '/_layout/dashboard/season/$seasonId/bulkgames/'
      path: '/bulkgames'
      fullPath: '/dashboard/season/$seasonId/bulkgames'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdBulkgamesIndexImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdImport
    }
    '/_layout/dashboard/season/$seasonId/metadata/': {
      id: '/_layout/dashboard/season/$seasonId/metadata/'
      path: '/metadata'
      fullPath: '/dashboard/season/$seasonId/metadata'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdMetadataIndexImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdImport
    }
    '/_layout/dashboard/season/$seasonId/newseries/': {
      id: '/_layout/dashboard/season/$seasonId/newseries/'
      path: '/newseries'
      fullPath: '/dashboard/season/$seasonId/newseries'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdNewseriesIndexImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdImport
    }
    '/_layout/dashboard/season/$seasonId/teamseason/': {
      id: '/_layout/dashboard/season/$seasonId/teamseason/'
      path: '/teamseason'
      fullPath: '/dashboard/season/$seasonId/teamseason'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdTeamseasonIndexImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdImport
    }
    '/_layout/dashboard/season/$seasonId/games/$serieId/$gameId': {
      id: '/_layout/dashboard/season/$seasonId/games/$serieId/$gameId'
      path: '/$gameId'
      fullPath: '/dashboard/season/$seasonId/games/$serieId/$gameId'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdGamesSerieIdImport
    }
    '/_layout/dashboard/season/$seasonId/games/$serieId/$gameId/delete': {
      id: '/_layout/dashboard/season/$seasonId/games/$serieId/$gameId/delete'
      path: '/delete'
      fullPath: '/dashboard/season/$seasonId/games/$serieId/$gameId/delete'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdDeleteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdImport
    }
    '/_layout/dashboard/season/$seasonId/games/$serieId/$gameId/edit': {
      id: '/_layout/dashboard/season/$seasonId/games/$serieId/$gameId/edit'
      path: '/edit'
      fullPath: '/dashboard/season/$seasonId/games/$serieId/$gameId/edit'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdEditImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdImport
    }
  }
}

// Create and export the route tree

interface LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdRouteChildren {
  LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdDeleteRoute: typeof LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdDeleteRoute
  LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdEditRoute: typeof LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdEditRoute
}

const LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdRouteChildren: LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdRouteChildren =
  {
    LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdDeleteRoute:
      LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdDeleteRoute,
    LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdEditRoute:
      LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdEditRoute,
  }

const LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdRouteWithChildren =
  LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdRoute._addFileChildren(
    LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdRouteChildren,
  )

interface LayoutDashboardSeasonSeasonIdGamesSerieIdRouteChildren {
  LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdRoute: typeof LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdRouteWithChildren
}

const LayoutDashboardSeasonSeasonIdGamesSerieIdRouteChildren: LayoutDashboardSeasonSeasonIdGamesSerieIdRouteChildren =
  {
    LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdRoute:
      LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdRouteWithChildren,
  }

const LayoutDashboardSeasonSeasonIdGamesSerieIdRouteWithChildren =
  LayoutDashboardSeasonSeasonIdGamesSerieIdRoute._addFileChildren(
    LayoutDashboardSeasonSeasonIdGamesSerieIdRouteChildren,
  )

interface LayoutDashboardSeasonSeasonIdRouteChildren {
  LayoutDashboardSeasonSeasonIdIndexRoute: typeof LayoutDashboardSeasonSeasonIdIndexRoute
  LayoutDashboardSeasonSeasonIdGamesSerieIdRoute: typeof LayoutDashboardSeasonSeasonIdGamesSerieIdRouteWithChildren
  LayoutDashboardSeasonSeasonIdBulkgamesIndexRoute: typeof LayoutDashboardSeasonSeasonIdBulkgamesIndexRoute
  LayoutDashboardSeasonSeasonIdMetadataIndexRoute: typeof LayoutDashboardSeasonSeasonIdMetadataIndexRoute
  LayoutDashboardSeasonSeasonIdNewseriesIndexRoute: typeof LayoutDashboardSeasonSeasonIdNewseriesIndexRoute
  LayoutDashboardSeasonSeasonIdTeamseasonIndexRoute: typeof LayoutDashboardSeasonSeasonIdTeamseasonIndexRoute
}

const LayoutDashboardSeasonSeasonIdRouteChildren: LayoutDashboardSeasonSeasonIdRouteChildren =
  {
    LayoutDashboardSeasonSeasonIdIndexRoute:
      LayoutDashboardSeasonSeasonIdIndexRoute,
    LayoutDashboardSeasonSeasonIdGamesSerieIdRoute:
      LayoutDashboardSeasonSeasonIdGamesSerieIdRouteWithChildren,
    LayoutDashboardSeasonSeasonIdBulkgamesIndexRoute:
      LayoutDashboardSeasonSeasonIdBulkgamesIndexRoute,
    LayoutDashboardSeasonSeasonIdMetadataIndexRoute:
      LayoutDashboardSeasonSeasonIdMetadataIndexRoute,
    LayoutDashboardSeasonSeasonIdNewseriesIndexRoute:
      LayoutDashboardSeasonSeasonIdNewseriesIndexRoute,
    LayoutDashboardSeasonSeasonIdTeamseasonIndexRoute:
      LayoutDashboardSeasonSeasonIdTeamseasonIndexRoute,
  }

const LayoutDashboardSeasonSeasonIdRouteWithChildren =
  LayoutDashboardSeasonSeasonIdRoute._addFileChildren(
    LayoutDashboardSeasonSeasonIdRouteChildren,
  )

interface LayoutDashboardRouteChildren {
  LayoutDashboardAddTeamsRoute: typeof LayoutDashboardAddTeamsRoute
  LayoutDashboardErrorsRoute: typeof LayoutDashboardErrorsRoute
  LayoutDashboardNewSeasonRoute: typeof LayoutDashboardNewSeasonRoute
  LayoutDashboardSeasonsRoute: typeof LayoutDashboardSeasonsRoute
  LayoutDashboardIndexRoute: typeof LayoutDashboardIndexRoute
  LayoutDashboardSeasonSeasonIdRoute: typeof LayoutDashboardSeasonSeasonIdRouteWithChildren
  LayoutDashboardTeamsIndexRoute: typeof LayoutDashboardTeamsIndexRoute
  LayoutDashboardTeamsTeamIdDeleteRoute: typeof LayoutDashboardTeamsTeamIdDeleteRoute
}

const LayoutDashboardRouteChildren: LayoutDashboardRouteChildren = {
  LayoutDashboardAddTeamsRoute: LayoutDashboardAddTeamsRoute,
  LayoutDashboardErrorsRoute: LayoutDashboardErrorsRoute,
  LayoutDashboardNewSeasonRoute: LayoutDashboardNewSeasonRoute,
  LayoutDashboardSeasonsRoute: LayoutDashboardSeasonsRoute,
  LayoutDashboardIndexRoute: LayoutDashboardIndexRoute,
  LayoutDashboardSeasonSeasonIdRoute:
    LayoutDashboardSeasonSeasonIdRouteWithChildren,
  LayoutDashboardTeamsIndexRoute: LayoutDashboardTeamsIndexRoute,
  LayoutDashboardTeamsTeamIdDeleteRoute: LayoutDashboardTeamsTeamIdDeleteRoute,
}

const LayoutDashboardRouteWithChildren = LayoutDashboardRoute._addFileChildren(
  LayoutDashboardRouteChildren,
)

interface LayoutMaratonRecordsRouteChildren {
  LayoutMaratonRecordsConcededRoute: typeof LayoutMaratonRecordsConcededRoute
  LayoutMaratonRecordsPointsRoute: typeof LayoutMaratonRecordsPointsRoute
  LayoutMaratonRecordsScoredRoute: typeof LayoutMaratonRecordsScoredRoute
  LayoutMaratonRecordsStreaksRoute: typeof LayoutMaratonRecordsStreaksRoute
  LayoutMaratonRecordsIndexRoute: typeof LayoutMaratonRecordsIndexRoute
}

const LayoutMaratonRecordsRouteChildren: LayoutMaratonRecordsRouteChildren = {
  LayoutMaratonRecordsConcededRoute: LayoutMaratonRecordsConcededRoute,
  LayoutMaratonRecordsPointsRoute: LayoutMaratonRecordsPointsRoute,
  LayoutMaratonRecordsScoredRoute: LayoutMaratonRecordsScoredRoute,
  LayoutMaratonRecordsStreaksRoute: LayoutMaratonRecordsStreaksRoute,
  LayoutMaratonRecordsIndexRoute: LayoutMaratonRecordsIndexRoute,
}

const LayoutMaratonRecordsRouteWithChildren =
  LayoutMaratonRecordsRoute._addFileChildren(LayoutMaratonRecordsRouteChildren)

interface LayoutMaratonTableRouteChildren {
  LayoutMaratonTableTableRoute: typeof LayoutMaratonTableTableRoute
}

const LayoutMaratonTableRouteChildren: LayoutMaratonTableRouteChildren = {
  LayoutMaratonTableTableRoute: LayoutMaratonTableTableRoute,
}

const LayoutMaratonTableRouteWithChildren =
  LayoutMaratonTableRoute._addFileChildren(LayoutMaratonTableRouteChildren)

interface LayoutMaratonRouteChildren {
  LayoutMaratonHelpRoute: typeof LayoutMaratonHelpRoute
  LayoutMaratonRecordsRoute: typeof LayoutMaratonRecordsRouteWithChildren
  LayoutMaratonTableRoute: typeof LayoutMaratonTableRouteWithChildren
}

const LayoutMaratonRouteChildren: LayoutMaratonRouteChildren = {
  LayoutMaratonHelpRoute: LayoutMaratonHelpRoute,
  LayoutMaratonRecordsRoute: LayoutMaratonRecordsRouteWithChildren,
  LayoutMaratonTableRoute: LayoutMaratonTableRouteWithChildren,
}

const LayoutMaratonRouteWithChildren = LayoutMaratonRoute._addFileChildren(
  LayoutMaratonRouteChildren,
)

interface LayoutSearchRouteChildren {
  LayoutSearchHelpRoute: typeof LayoutSearchHelpRoute
  LayoutSearchIndexRoute: typeof LayoutSearchIndexRoute
}

const LayoutSearchRouteChildren: LayoutSearchRouteChildren = {
  LayoutSearchHelpRoute: LayoutSearchHelpRoute,
  LayoutSearchIndexRoute: LayoutSearchIndexRoute,
}

const LayoutSearchRouteWithChildren = LayoutSearchRoute._addFileChildren(
  LayoutSearchRouteChildren,
)

interface LayoutSeasonSeasonIdRouteChildren {
  LayoutSeasonSeasonIdDevelopmentRoute: typeof LayoutSeasonSeasonIdDevelopmentRoute
  LayoutSeasonSeasonIdGamesRoute: typeof LayoutSeasonSeasonIdGamesRoute
  LayoutSeasonSeasonIdPlayoffRoute: typeof LayoutSeasonSeasonIdPlayoffRoute
  LayoutSeasonSeasonIdStatsRoute: typeof LayoutSeasonSeasonIdStatsRoute
  LayoutSeasonSeasonIdMapLazyRoute: typeof LayoutSeasonSeasonIdMapLazyRoute
  LayoutSeasonSeasonIdTablesIndexRoute: typeof LayoutSeasonSeasonIdTablesIndexRoute
  LayoutSeasonSeasonIdTablesTableTableRoute: typeof LayoutSeasonSeasonIdTablesTableTableRoute
}

const LayoutSeasonSeasonIdRouteChildren: LayoutSeasonSeasonIdRouteChildren = {
  LayoutSeasonSeasonIdDevelopmentRoute: LayoutSeasonSeasonIdDevelopmentRoute,
  LayoutSeasonSeasonIdGamesRoute: LayoutSeasonSeasonIdGamesRoute,
  LayoutSeasonSeasonIdPlayoffRoute: LayoutSeasonSeasonIdPlayoffRoute,
  LayoutSeasonSeasonIdStatsRoute: LayoutSeasonSeasonIdStatsRoute,
  LayoutSeasonSeasonIdMapLazyRoute: LayoutSeasonSeasonIdMapLazyRoute,
  LayoutSeasonSeasonIdTablesIndexRoute: LayoutSeasonSeasonIdTablesIndexRoute,
  LayoutSeasonSeasonIdTablesTableTableRoute:
    LayoutSeasonSeasonIdTablesTableTableRoute,
}

const LayoutSeasonSeasonIdRouteWithChildren =
  LayoutSeasonSeasonIdRoute._addFileChildren(LayoutSeasonSeasonIdRouteChildren)

interface LayoutSeasonRouteChildren {
  LayoutSeasonSeasonIdRoute: typeof LayoutSeasonSeasonIdRouteWithChildren
}

const LayoutSeasonRouteChildren: LayoutSeasonRouteChildren = {
  LayoutSeasonSeasonIdRoute: LayoutSeasonSeasonIdRouteWithChildren,
}

const LayoutSeasonRouteWithChildren = LayoutSeasonRoute._addFileChildren(
  LayoutSeasonRouteChildren,
)

interface LayoutTeamRouteChildren {
  LayoutTeamTeamIdRoute: typeof LayoutTeamTeamIdRoute
}

const LayoutTeamRouteChildren: LayoutTeamRouteChildren = {
  LayoutTeamTeamIdRoute: LayoutTeamTeamIdRoute,
}

const LayoutTeamRouteWithChildren = LayoutTeamRoute._addFileChildren(
  LayoutTeamRouteChildren,
)

interface LayoutTeamsRouteChildren {
  LayoutTeamsCompareRoute: typeof LayoutTeamsCompareRoute
  LayoutTeamsSelectionRoute: typeof LayoutTeamsSelectionRoute
  LayoutTeamsMapLazyRoute: typeof LayoutTeamsMapLazyRoute
  LayoutTeamsIndexRoute: typeof LayoutTeamsIndexRoute
}

const LayoutTeamsRouteChildren: LayoutTeamsRouteChildren = {
  LayoutTeamsCompareRoute: LayoutTeamsCompareRoute,
  LayoutTeamsSelectionRoute: LayoutTeamsSelectionRoute,
  LayoutTeamsMapLazyRoute: LayoutTeamsMapLazyRoute,
  LayoutTeamsIndexRoute: LayoutTeamsIndexRoute,
}

const LayoutTeamsRouteWithChildren = LayoutTeamsRoute._addFileChildren(
  LayoutTeamsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutDashboardRoute: typeof LayoutDashboardRouteWithChildren
  LayoutMaratonRoute: typeof LayoutMaratonRouteWithChildren
  LayoutSearchRoute: typeof LayoutSearchRouteWithChildren
  LayoutSeasonRoute: typeof LayoutSeasonRouteWithChildren
  LayoutSeasonsRoute: typeof LayoutSeasonsRoute
  LayoutTeamRoute: typeof LayoutTeamRouteWithChildren
  LayoutTeamsRoute: typeof LayoutTeamsRouteWithChildren
  LayoutAboutLazyRoute: typeof LayoutAboutLazyRoute
  LayoutUnauthorizedLazyRoute: typeof LayoutUnauthorizedLazyRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardRoute: LayoutDashboardRouteWithChildren,
  LayoutMaratonRoute: LayoutMaratonRouteWithChildren,
  LayoutSearchRoute: LayoutSearchRouteWithChildren,
  LayoutSeasonRoute: LayoutSeasonRouteWithChildren,
  LayoutSeasonsRoute: LayoutSeasonsRoute,
  LayoutTeamRoute: LayoutTeamRouteWithChildren,
  LayoutTeamsRoute: LayoutTeamsRouteWithChildren,
  LayoutAboutLazyRoute: LayoutAboutLazyRoute,
  LayoutUnauthorizedLazyRoute: LayoutUnauthorizedLazyRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/dashboard': typeof LayoutDashboardRouteWithChildren
  '/maraton': typeof LayoutMaratonRouteWithChildren
  '/search': typeof LayoutSearchRouteWithChildren
  '/season': typeof LayoutSeasonRouteWithChildren
  '/seasons': typeof LayoutSeasonsRoute
  '/team': typeof LayoutTeamRouteWithChildren
  '/teams': typeof LayoutTeamsRouteWithChildren
  '/about': typeof LayoutAboutLazyRoute
  '/unauthorized': typeof LayoutUnauthorizedLazyRoute
  '/': typeof LayoutIndexRoute
  '/dashboard/addTeams': typeof LayoutDashboardAddTeamsRoute
  '/dashboard/errors': typeof LayoutDashboardErrorsRoute
  '/dashboard/newSeason': typeof LayoutDashboardNewSeasonRoute
  '/dashboard/seasons': typeof LayoutDashboardSeasonsRoute
  '/maraton/help': typeof LayoutMaratonHelpRoute
  '/maraton/records': typeof LayoutMaratonRecordsRouteWithChildren
  '/maraton/table': typeof LayoutMaratonTableRouteWithChildren
  '/search/help': typeof LayoutSearchHelpRoute
  '/season/$seasonId': typeof LayoutSeasonSeasonIdRouteWithChildren
  '/team/$teamId': typeof LayoutTeamTeamIdRoute
  '/teams/compare': typeof LayoutTeamsCompareRoute
  '/teams/selection': typeof LayoutTeamsSelectionRoute
  '/teams/map': typeof LayoutTeamsMapLazyRoute
  '/dashboard/': typeof LayoutDashboardIndexRoute
  '/search/': typeof LayoutSearchIndexRoute
  '/teams/': typeof LayoutTeamsIndexRoute
  '/dashboard/season/$seasonId': typeof LayoutDashboardSeasonSeasonIdRouteWithChildren
  '/maraton/records/conceded': typeof LayoutMaratonRecordsConcededRoute
  '/maraton/records/points': typeof LayoutMaratonRecordsPointsRoute
  '/maraton/records/scored': typeof LayoutMaratonRecordsScoredRoute
  '/maraton/records/streaks': typeof LayoutMaratonRecordsStreaksRoute
  '/maraton/table/$table': typeof LayoutMaratonTableTableRoute
  '/season/$seasonId/development': typeof LayoutSeasonSeasonIdDevelopmentRoute
  '/season/$seasonId/games': typeof LayoutSeasonSeasonIdGamesRoute
  '/season/$seasonId/playoff': typeof LayoutSeasonSeasonIdPlayoffRoute
  '/season/$seasonId/stats': typeof LayoutSeasonSeasonIdStatsRoute
  '/season/$seasonId/map': typeof LayoutSeasonSeasonIdMapLazyRoute
  '/dashboard/teams': typeof LayoutDashboardTeamsIndexRoute
  '/maraton/records/': typeof LayoutMaratonRecordsIndexRoute
  '/dashboard/teams/$teamId/delete': typeof LayoutDashboardTeamsTeamIdDeleteRoute
  '/dashboard/season/$seasonId/': typeof LayoutDashboardSeasonSeasonIdIndexRoute
  '/season/$seasonId/tables': typeof LayoutSeasonSeasonIdTablesIndexRoute
  '/dashboard/season/$seasonId/games/$serieId': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdRouteWithChildren
  '/season/$seasonId/tables/$table': typeof LayoutSeasonSeasonIdTablesTableTableRoute
  '/dashboard/season/$seasonId/bulkgames': typeof LayoutDashboardSeasonSeasonIdBulkgamesIndexRoute
  '/dashboard/season/$seasonId/metadata': typeof LayoutDashboardSeasonSeasonIdMetadataIndexRoute
  '/dashboard/season/$seasonId/newseries': typeof LayoutDashboardSeasonSeasonIdNewseriesIndexRoute
  '/dashboard/season/$seasonId/teamseason': typeof LayoutDashboardSeasonSeasonIdTeamseasonIndexRoute
  '/dashboard/season/$seasonId/games/$serieId/$gameId': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdRouteWithChildren
  '/dashboard/season/$seasonId/games/$serieId/$gameId/delete': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdDeleteRoute
  '/dashboard/season/$seasonId/games/$serieId/$gameId/edit': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdEditRoute
}

export interface FileRoutesByTo {
  '/maraton': typeof LayoutMaratonRouteWithChildren
  '/season': typeof LayoutSeasonRouteWithChildren
  '/seasons': typeof LayoutSeasonsRoute
  '/team': typeof LayoutTeamRouteWithChildren
  '/about': typeof LayoutAboutLazyRoute
  '/unauthorized': typeof LayoutUnauthorizedLazyRoute
  '/': typeof LayoutIndexRoute
  '/dashboard/addTeams': typeof LayoutDashboardAddTeamsRoute
  '/dashboard/errors': typeof LayoutDashboardErrorsRoute
  '/dashboard/newSeason': typeof LayoutDashboardNewSeasonRoute
  '/dashboard/seasons': typeof LayoutDashboardSeasonsRoute
  '/maraton/help': typeof LayoutMaratonHelpRoute
  '/maraton/table': typeof LayoutMaratonTableRouteWithChildren
  '/search/help': typeof LayoutSearchHelpRoute
  '/season/$seasonId': typeof LayoutSeasonSeasonIdRouteWithChildren
  '/team/$teamId': typeof LayoutTeamTeamIdRoute
  '/teams/compare': typeof LayoutTeamsCompareRoute
  '/teams/selection': typeof LayoutTeamsSelectionRoute
  '/teams/map': typeof LayoutTeamsMapLazyRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/search': typeof LayoutSearchIndexRoute
  '/teams': typeof LayoutTeamsIndexRoute
  '/maraton/records/conceded': typeof LayoutMaratonRecordsConcededRoute
  '/maraton/records/points': typeof LayoutMaratonRecordsPointsRoute
  '/maraton/records/scored': typeof LayoutMaratonRecordsScoredRoute
  '/maraton/records/streaks': typeof LayoutMaratonRecordsStreaksRoute
  '/maraton/table/$table': typeof LayoutMaratonTableTableRoute
  '/season/$seasonId/development': typeof LayoutSeasonSeasonIdDevelopmentRoute
  '/season/$seasonId/games': typeof LayoutSeasonSeasonIdGamesRoute
  '/season/$seasonId/playoff': typeof LayoutSeasonSeasonIdPlayoffRoute
  '/season/$seasonId/stats': typeof LayoutSeasonSeasonIdStatsRoute
  '/season/$seasonId/map': typeof LayoutSeasonSeasonIdMapLazyRoute
  '/dashboard/teams': typeof LayoutDashboardTeamsIndexRoute
  '/maraton/records': typeof LayoutMaratonRecordsIndexRoute
  '/dashboard/teams/$teamId/delete': typeof LayoutDashboardTeamsTeamIdDeleteRoute
  '/dashboard/season/$seasonId': typeof LayoutDashboardSeasonSeasonIdIndexRoute
  '/season/$seasonId/tables': typeof LayoutSeasonSeasonIdTablesIndexRoute
  '/dashboard/season/$seasonId/games/$serieId': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdRouteWithChildren
  '/season/$seasonId/tables/$table': typeof LayoutSeasonSeasonIdTablesTableTableRoute
  '/dashboard/season/$seasonId/bulkgames': typeof LayoutDashboardSeasonSeasonIdBulkgamesIndexRoute
  '/dashboard/season/$seasonId/metadata': typeof LayoutDashboardSeasonSeasonIdMetadataIndexRoute
  '/dashboard/season/$seasonId/newseries': typeof LayoutDashboardSeasonSeasonIdNewseriesIndexRoute
  '/dashboard/season/$seasonId/teamseason': typeof LayoutDashboardSeasonSeasonIdTeamseasonIndexRoute
  '/dashboard/season/$seasonId/games/$serieId/$gameId': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdRouteWithChildren
  '/dashboard/season/$seasonId/games/$serieId/$gameId/delete': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdDeleteRoute
  '/dashboard/season/$seasonId/games/$serieId/$gameId/edit': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/dashboard': typeof LayoutDashboardRouteWithChildren
  '/_layout/maraton': typeof LayoutMaratonRouteWithChildren
  '/_layout/search': typeof LayoutSearchRouteWithChildren
  '/_layout/season': typeof LayoutSeasonRouteWithChildren
  '/_layout/seasons': typeof LayoutSeasonsRoute
  '/_layout/team': typeof LayoutTeamRouteWithChildren
  '/_layout/teams': typeof LayoutTeamsRouteWithChildren
  '/_layout/about': typeof LayoutAboutLazyRoute
  '/_layout/unauthorized': typeof LayoutUnauthorizedLazyRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/dashboard/addTeams': typeof LayoutDashboardAddTeamsRoute
  '/_layout/dashboard/errors': typeof LayoutDashboardErrorsRoute
  '/_layout/dashboard/newSeason': typeof LayoutDashboardNewSeasonRoute
  '/_layout/dashboard/seasons': typeof LayoutDashboardSeasonsRoute
  '/_layout/maraton/help': typeof LayoutMaratonHelpRoute
  '/_layout/maraton/records': typeof LayoutMaratonRecordsRouteWithChildren
  '/_layout/maraton/table': typeof LayoutMaratonTableRouteWithChildren
  '/_layout/search/help': typeof LayoutSearchHelpRoute
  '/_layout/season/$seasonId': typeof LayoutSeasonSeasonIdRouteWithChildren
  '/_layout/team/$teamId': typeof LayoutTeamTeamIdRoute
  '/_layout/teams/compare': typeof LayoutTeamsCompareRoute
  '/_layout/teams/selection': typeof LayoutTeamsSelectionRoute
  '/_layout/teams/map': typeof LayoutTeamsMapLazyRoute
  '/_layout/dashboard/': typeof LayoutDashboardIndexRoute
  '/_layout/search/': typeof LayoutSearchIndexRoute
  '/_layout/teams/': typeof LayoutTeamsIndexRoute
  '/_layout/dashboard/season/$seasonId': typeof LayoutDashboardSeasonSeasonIdRouteWithChildren
  '/_layout/maraton/records/conceded': typeof LayoutMaratonRecordsConcededRoute
  '/_layout/maraton/records/points': typeof LayoutMaratonRecordsPointsRoute
  '/_layout/maraton/records/scored': typeof LayoutMaratonRecordsScoredRoute
  '/_layout/maraton/records/streaks': typeof LayoutMaratonRecordsStreaksRoute
  '/_layout/maraton/table/$table': typeof LayoutMaratonTableTableRoute
  '/_layout/season/$seasonId/development': typeof LayoutSeasonSeasonIdDevelopmentRoute
  '/_layout/season/$seasonId/games': typeof LayoutSeasonSeasonIdGamesRoute
  '/_layout/season/$seasonId/playoff': typeof LayoutSeasonSeasonIdPlayoffRoute
  '/_layout/season/$seasonId/stats': typeof LayoutSeasonSeasonIdStatsRoute
  '/_layout/season/$seasonId/map': typeof LayoutSeasonSeasonIdMapLazyRoute
  '/_layout/dashboard/teams/': typeof LayoutDashboardTeamsIndexRoute
  '/_layout/maraton/records/': typeof LayoutMaratonRecordsIndexRoute
  '/_layout/dashboard/teams/$teamId/delete': typeof LayoutDashboardTeamsTeamIdDeleteRoute
  '/_layout/dashboard/season/$seasonId/': typeof LayoutDashboardSeasonSeasonIdIndexRoute
  '/_layout/season/$seasonId/tables/': typeof LayoutSeasonSeasonIdTablesIndexRoute
  '/_layout/dashboard/season/$seasonId/games/$serieId': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdRouteWithChildren
  '/_layout/season/$seasonId/tables/_table/$table': typeof LayoutSeasonSeasonIdTablesTableTableRoute
  '/_layout/dashboard/season/$seasonId/bulkgames/': typeof LayoutDashboardSeasonSeasonIdBulkgamesIndexRoute
  '/_layout/dashboard/season/$seasonId/metadata/': typeof LayoutDashboardSeasonSeasonIdMetadataIndexRoute
  '/_layout/dashboard/season/$seasonId/newseries/': typeof LayoutDashboardSeasonSeasonIdNewseriesIndexRoute
  '/_layout/dashboard/season/$seasonId/teamseason/': typeof LayoutDashboardSeasonSeasonIdTeamseasonIndexRoute
  '/_layout/dashboard/season/$seasonId/games/$serieId/$gameId': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdRouteWithChildren
  '/_layout/dashboard/season/$seasonId/games/$serieId/$gameId/delete': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdDeleteRoute
  '/_layout/dashboard/season/$seasonId/games/$serieId/$gameId/edit': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdGameIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/dashboard'
    | '/maraton'
    | '/search'
    | '/season'
    | '/seasons'
    | '/team'
    | '/teams'
    | '/about'
    | '/unauthorized'
    | '/'
    | '/dashboard/addTeams'
    | '/dashboard/errors'
    | '/dashboard/newSeason'
    | '/dashboard/seasons'
    | '/maraton/help'
    | '/maraton/records'
    | '/maraton/table'
    | '/search/help'
    | '/season/$seasonId'
    | '/team/$teamId'
    | '/teams/compare'
    | '/teams/selection'
    | '/teams/map'
    | '/dashboard/'
    | '/search/'
    | '/teams/'
    | '/dashboard/season/$seasonId'
    | '/maraton/records/conceded'
    | '/maraton/records/points'
    | '/maraton/records/scored'
    | '/maraton/records/streaks'
    | '/maraton/table/$table'
    | '/season/$seasonId/development'
    | '/season/$seasonId/games'
    | '/season/$seasonId/playoff'
    | '/season/$seasonId/stats'
    | '/season/$seasonId/map'
    | '/dashboard/teams'
    | '/maraton/records/'
    | '/dashboard/teams/$teamId/delete'
    | '/dashboard/season/$seasonId/'
    | '/season/$seasonId/tables'
    | '/dashboard/season/$seasonId/games/$serieId'
    | '/season/$seasonId/tables/$table'
    | '/dashboard/season/$seasonId/bulkgames'
    | '/dashboard/season/$seasonId/metadata'
    | '/dashboard/season/$seasonId/newseries'
    | '/dashboard/season/$seasonId/teamseason'
    | '/dashboard/season/$seasonId/games/$serieId/$gameId'
    | '/dashboard/season/$seasonId/games/$serieId/$gameId/delete'
    | '/dashboard/season/$seasonId/games/$serieId/$gameId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/maraton'
    | '/season'
    | '/seasons'
    | '/team'
    | '/about'
    | '/unauthorized'
    | '/'
    | '/dashboard/addTeams'
    | '/dashboard/errors'
    | '/dashboard/newSeason'
    | '/dashboard/seasons'
    | '/maraton/help'
    | '/maraton/table'
    | '/search/help'
    | '/season/$seasonId'
    | '/team/$teamId'
    | '/teams/compare'
    | '/teams/selection'
    | '/teams/map'
    | '/dashboard'
    | '/search'
    | '/teams'
    | '/maraton/records/conceded'
    | '/maraton/records/points'
    | '/maraton/records/scored'
    | '/maraton/records/streaks'
    | '/maraton/table/$table'
    | '/season/$seasonId/development'
    | '/season/$seasonId/games'
    | '/season/$seasonId/playoff'
    | '/season/$seasonId/stats'
    | '/season/$seasonId/map'
    | '/dashboard/teams'
    | '/maraton/records'
    | '/dashboard/teams/$teamId/delete'
    | '/dashboard/season/$seasonId'
    | '/season/$seasonId/tables'
    | '/dashboard/season/$seasonId/games/$serieId'
    | '/season/$seasonId/tables/$table'
    | '/dashboard/season/$seasonId/bulkgames'
    | '/dashboard/season/$seasonId/metadata'
    | '/dashboard/season/$seasonId/newseries'
    | '/dashboard/season/$seasonId/teamseason'
    | '/dashboard/season/$seasonId/games/$serieId/$gameId'
    | '/dashboard/season/$seasonId/games/$serieId/$gameId/delete'
    | '/dashboard/season/$seasonId/games/$serieId/$gameId/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/dashboard'
    | '/_layout/maraton'
    | '/_layout/search'
    | '/_layout/season'
    | '/_layout/seasons'
    | '/_layout/team'
    | '/_layout/teams'
    | '/_layout/about'
    | '/_layout/unauthorized'
    | '/_layout/'
    | '/_layout/dashboard/addTeams'
    | '/_layout/dashboard/errors'
    | '/_layout/dashboard/newSeason'
    | '/_layout/dashboard/seasons'
    | '/_layout/maraton/help'
    | '/_layout/maraton/records'
    | '/_layout/maraton/table'
    | '/_layout/search/help'
    | '/_layout/season/$seasonId'
    | '/_layout/team/$teamId'
    | '/_layout/teams/compare'
    | '/_layout/teams/selection'
    | '/_layout/teams/map'
    | '/_layout/dashboard/'
    | '/_layout/search/'
    | '/_layout/teams/'
    | '/_layout/dashboard/season/$seasonId'
    | '/_layout/maraton/records/conceded'
    | '/_layout/maraton/records/points'
    | '/_layout/maraton/records/scored'
    | '/_layout/maraton/records/streaks'
    | '/_layout/maraton/table/$table'
    | '/_layout/season/$seasonId/development'
    | '/_layout/season/$seasonId/games'
    | '/_layout/season/$seasonId/playoff'
    | '/_layout/season/$seasonId/stats'
    | '/_layout/season/$seasonId/map'
    | '/_layout/dashboard/teams/'
    | '/_layout/maraton/records/'
    | '/_layout/dashboard/teams/$teamId/delete'
    | '/_layout/dashboard/season/$seasonId/'
    | '/_layout/season/$seasonId/tables/'
    | '/_layout/dashboard/season/$seasonId/games/$serieId'
    | '/_layout/season/$seasonId/tables/_table/$table'
    | '/_layout/dashboard/season/$seasonId/bulkgames/'
    | '/_layout/dashboard/season/$seasonId/metadata/'
    | '/_layout/dashboard/season/$seasonId/newseries/'
    | '/_layout/dashboard/season/$seasonId/teamseason/'
    | '/_layout/dashboard/season/$seasonId/games/$serieId/$gameId'
    | '/_layout/dashboard/season/$seasonId/games/$serieId/$gameId/delete'
    | '/_layout/dashboard/season/$seasonId/games/$serieId/$gameId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/dashboard",
        "/_layout/maraton",
        "/_layout/search",
        "/_layout/season",
        "/_layout/seasons",
        "/_layout/team",
        "/_layout/teams",
        "/_layout/about",
        "/_layout/unauthorized",
        "/_layout/"
      ]
    },
    "/_layout/dashboard": {
      "filePath": "_layout/dashboard.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/dashboard/addTeams",
        "/_layout/dashboard/errors",
        "/_layout/dashboard/newSeason",
        "/_layout/dashboard/seasons",
        "/_layout/dashboard/",
        "/_layout/dashboard/season/$seasonId",
        "/_layout/dashboard/teams/",
        "/_layout/dashboard/teams/$teamId/delete"
      ]
    },
    "/_layout/maraton": {
      "filePath": "_layout/maraton.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/maraton/help",
        "/_layout/maraton/records",
        "/_layout/maraton/table"
      ]
    },
    "/_layout/search": {
      "filePath": "_layout/search.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/search/help",
        "/_layout/search/"
      ]
    },
    "/_layout/season": {
      "filePath": "_layout/season.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/season/$seasonId"
      ]
    },
    "/_layout/seasons": {
      "filePath": "_layout/seasons.tsx",
      "parent": "/_layout"
    },
    "/_layout/team": {
      "filePath": "_layout/team.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/team/$teamId"
      ]
    },
    "/_layout/teams": {
      "filePath": "_layout/teams.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/teams/compare",
        "/_layout/teams/selection",
        "/_layout/teams/map",
        "/_layout/teams/"
      ]
    },
    "/_layout/about": {
      "filePath": "_layout/about.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/unauthorized": {
      "filePath": "_layout/unauthorized.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/addTeams": {
      "filePath": "_layout/dashboard/addTeams.tsx",
      "parent": "/_layout/dashboard"
    },
    "/_layout/dashboard/errors": {
      "filePath": "_layout/dashboard/errors.tsx",
      "parent": "/_layout/dashboard"
    },
    "/_layout/dashboard/newSeason": {
      "filePath": "_layout/dashboard/newSeason.tsx",
      "parent": "/_layout/dashboard"
    },
    "/_layout/dashboard/seasons": {
      "filePath": "_layout/dashboard/seasons.tsx",
      "parent": "/_layout/dashboard"
    },
    "/_layout/maraton/help": {
      "filePath": "_layout/maraton/help.tsx",
      "parent": "/_layout/maraton"
    },
    "/_layout/maraton/records": {
      "filePath": "_layout/maraton/records.tsx",
      "parent": "/_layout/maraton",
      "children": [
        "/_layout/maraton/records/conceded",
        "/_layout/maraton/records/points",
        "/_layout/maraton/records/scored",
        "/_layout/maraton/records/streaks",
        "/_layout/maraton/records/"
      ]
    },
    "/_layout/maraton/table": {
      "filePath": "_layout/maraton/table.tsx",
      "parent": "/_layout/maraton",
      "children": [
        "/_layout/maraton/table/$table"
      ]
    },
    "/_layout/search/help": {
      "filePath": "_layout/search/help.tsx",
      "parent": "/_layout/search"
    },
    "/_layout/season/$seasonId": {
      "filePath": "_layout/season/$seasonId.tsx",
      "parent": "/_layout/season",
      "children": [
        "/_layout/season/$seasonId/development",
        "/_layout/season/$seasonId/games",
        "/_layout/season/$seasonId/playoff",
        "/_layout/season/$seasonId/stats",
        "/_layout/season/$seasonId/map",
        "/_layout/season/$seasonId/tables/",
        "/_layout/season/$seasonId/tables/_table/$table"
      ]
    },
    "/_layout/team/$teamId": {
      "filePath": "_layout/team/$teamId.tsx",
      "parent": "/_layout/team"
    },
    "/_layout/teams/compare": {
      "filePath": "_layout/teams/compare.tsx",
      "parent": "/_layout/teams"
    },
    "/_layout/teams/selection": {
      "filePath": "_layout/teams/selection.tsx",
      "parent": "/_layout/teams"
    },
    "/_layout/teams/map": {
      "filePath": "_layout/teams/map.lazy.tsx",
      "parent": "/_layout/teams"
    },
    "/_layout/dashboard/": {
      "filePath": "_layout/dashboard/index.tsx",
      "parent": "/_layout/dashboard"
    },
    "/_layout/search/": {
      "filePath": "_layout/search/index.tsx",
      "parent": "/_layout/search"
    },
    "/_layout/teams/": {
      "filePath": "_layout/teams/index.tsx",
      "parent": "/_layout/teams"
    },
    "/_layout/dashboard/season/$seasonId": {
      "filePath": "_layout/dashboard/season/$seasonId.tsx",
      "parent": "/_layout/dashboard",
      "children": [
        "/_layout/dashboard/season/$seasonId/",
        "/_layout/dashboard/season/$seasonId/games/$serieId",
        "/_layout/dashboard/season/$seasonId/bulkgames/",
        "/_layout/dashboard/season/$seasonId/metadata/",
        "/_layout/dashboard/season/$seasonId/newseries/",
        "/_layout/dashboard/season/$seasonId/teamseason/"
      ]
    },
    "/_layout/maraton/records/conceded": {
      "filePath": "_layout/maraton/records/conceded.tsx",
      "parent": "/_layout/maraton/records"
    },
    "/_layout/maraton/records/points": {
      "filePath": "_layout/maraton/records/points.tsx",
      "parent": "/_layout/maraton/records"
    },
    "/_layout/maraton/records/scored": {
      "filePath": "_layout/maraton/records/scored.tsx",
      "parent": "/_layout/maraton/records"
    },
    "/_layout/maraton/records/streaks": {
      "filePath": "_layout/maraton/records/streaks.tsx",
      "parent": "/_layout/maraton/records"
    },
    "/_layout/maraton/table/$table": {
      "filePath": "_layout/maraton/table/$table.tsx",
      "parent": "/_layout/maraton/table"
    },
    "/_layout/season/$seasonId/development": {
      "filePath": "_layout/season/$seasonId.development.tsx",
      "parent": "/_layout/season/$seasonId"
    },
    "/_layout/season/$seasonId/games": {
      "filePath": "_layout/season/$seasonId.games.tsx",
      "parent": "/_layout/season/$seasonId"
    },
    "/_layout/season/$seasonId/playoff": {
      "filePath": "_layout/season/$seasonId.playoff.tsx",
      "parent": "/_layout/season/$seasonId"
    },
    "/_layout/season/$seasonId/stats": {
      "filePath": "_layout/season/$seasonId.stats.tsx",
      "parent": "/_layout/season/$seasonId"
    },
    "/_layout/season/$seasonId/map": {
      "filePath": "_layout/season/$seasonId.map.lazy.tsx",
      "parent": "/_layout/season/$seasonId"
    },
    "/_layout/dashboard/teams/": {
      "filePath": "_layout/dashboard/teams/index.tsx",
      "parent": "/_layout/dashboard"
    },
    "/_layout/maraton/records/": {
      "filePath": "_layout/maraton/records/index.tsx",
      "parent": "/_layout/maraton/records"
    },
    "/_layout/dashboard/teams/$teamId/delete": {
      "filePath": "_layout/dashboard/teams/$teamId/delete.tsx",
      "parent": "/_layout/dashboard"
    },
    "/_layout/dashboard/season/$seasonId/": {
      "filePath": "_layout/dashboard/season/$seasonId/index.tsx",
      "parent": "/_layout/dashboard/season/$seasonId"
    },
    "/_layout/season/$seasonId/tables/": {
      "filePath": "_layout/season/$seasonId/tables/index.tsx",
      "parent": "/_layout/season/$seasonId"
    },
    "/_layout/dashboard/season/$seasonId/games/$serieId": {
      "filePath": "_layout/dashboard/season/$seasonId/games/$serieId.tsx",
      "parent": "/_layout/dashboard/season/$seasonId",
      "children": [
        "/_layout/dashboard/season/$seasonId/games/$serieId/$gameId"
      ]
    },
    "/_layout/season/$seasonId/tables/_table/$table": {
      "filePath": "_layout/season/$seasonId/tables/_table/$table.tsx",
      "parent": "/_layout/season/$seasonId"
    },
    "/_layout/dashboard/season/$seasonId/bulkgames/": {
      "filePath": "_layout/dashboard/season/$seasonId/bulkgames/index.tsx",
      "parent": "/_layout/dashboard/season/$seasonId"
    },
    "/_layout/dashboard/season/$seasonId/metadata/": {
      "filePath": "_layout/dashboard/season/$seasonId/metadata/index.tsx",
      "parent": "/_layout/dashboard/season/$seasonId"
    },
    "/_layout/dashboard/season/$seasonId/newseries/": {
      "filePath": "_layout/dashboard/season/$seasonId/newseries/index.tsx",
      "parent": "/_layout/dashboard/season/$seasonId"
    },
    "/_layout/dashboard/season/$seasonId/teamseason/": {
      "filePath": "_layout/dashboard/season/$seasonId/teamseason_/index.tsx",
      "parent": "/_layout/dashboard/season/$seasonId"
    },
    "/_layout/dashboard/season/$seasonId/games/$serieId/$gameId": {
      "filePath": "_layout/dashboard/season/$seasonId/games/$serieId/$gameId.tsx",
      "parent": "/_layout/dashboard/season/$seasonId/games/$serieId",
      "children": [
        "/_layout/dashboard/season/$seasonId/games/$serieId/$gameId/delete",
        "/_layout/dashboard/season/$seasonId/games/$serieId/$gameId/edit"
      ]
    },
    "/_layout/dashboard/season/$seasonId/games/$serieId/$gameId/delete": {
      "filePath": "_layout/dashboard/season/$seasonId/games/$serieId/$gameId/delete.tsx",
      "parent": "/_layout/dashboard/season/$seasonId/games/$serieId/$gameId"
    },
    "/_layout/dashboard/season/$seasonId/games/$serieId/$gameId/edit": {
      "filePath": "_layout/dashboard/season/$seasonId/games/$serieId/$gameId/edit.tsx",
      "parent": "/_layout/dashboard/season/$seasonId/games/$serieId/$gameId"
    }
  }
}
ROUTE_MANIFEST_END */
